[tool] Fix get-contacts in case of no IRC nick
There are some cases when there is no IRC nick added to PTL or release
liaison in governance repository in reference/projects.yaml, only a
'null' value is added. In such cases now get-contacts runs to error[1].
This fix avoid to call strip() to None.

[1] File "openstack_releases/cmds/get_contacts.py", line 30, in __init__
    self.irc = contact_data['irc'].strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'NoneType' object has no attribute 'strip'

Change-Id: Idae4cac1a366455eb708a5215e0cc0debf8ebd2e
Signed-off-by: Elod Illes <elod.illes@est.tech>