Fix new-release command for cycle independent projects
new-release command fails for cycle 'independent' projects with:
KeyError: '_independent'
as there is no such 'series' key when we load series_status_data for
checking release-id of the used series. Since this is needed only
for <series>-eol and <series>-eol checking, let's skip these checks
in case of independent series.

Change-Id: Id12b15af4e9507307b0e562648214b46c5c53aaa